//App action
export const SAVE_IS_LOGIN = 'SAVE_IS_LOGIN'
export const SAVE_ACCOUNT = 'SAVE_ACCOUNT'
export const SAVE_IS_SHOPPING_CART_READY = 'SAVE_IS_SHOPPING_CART_READY'
export const SAVE_AVATAR = 'SAVE_AVATAR'
export const SAVE_SELECTED_VOUCHER = 'SAVE_SELECTED_VOUCHER'

//Notification action
export const SAVE_UNSEEN_NOTIFICATION_QUANTITY = 'SAVE_UNSEEN_NOTIFICATION_QUANTITY'
